import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import SignIn from '../screen/sign-in'
import HomePage from '../screen/home'
import { customUseContext } from '../context'

const Home: NextPage = () => {
  const { isLoggedIn } = customUseContext()

  return (
    <div className={styles.container}>

      <Head>
        <title>Real Time App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoggedIn ? <HomePage /> : <SignIn /> }

    </div>
  )
}

export default Home
